import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { AdminAuthProvider } from "./context/adminAuthcontext";
import { PermissionProvider } from "./hooks/usepermission";
import { BottomSheetProvider } from "./context/BottomSheetAdmin";
import { RouteProtection } from "./hooks/routeprotection";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AdminAuthProvider>
          <RouteProtection>
            <BottomSheetProvider>
              {/* <PermissionProvider> */}
              <div className=" min-h-screen flex flex-col antialiased">
                {children}
              </div>
            </BottomSheetProvider>
          </RouteProtection>

          {/* </PermissionProvider> */}
        </AdminAuthProvider>
      </body>
    </html>
  );
}
